services:
  backend:
    build: ./backend
    image: esprit-hack-backend-img
    container_name: esprit-hack-backend
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - MONGODB_URI=${MONGODB_URI}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build: ./client
    image: esprit-hack-frontend-img
    container_name: esprit-hack-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:4000/api
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
